# docker-compose.yml

version: '3.8'

services:
  app:
    build: .
    restart: always
    volumes:
      - .:/app # Mapeia o código para desenvolvimento (hot-reload)
    ports:
      - "8000:8000"
    env_file:
      - ./.env # Carrega as variáveis de ambiente do arquivo .env
    depends_on:
      - db # Garante que o serviço 'db' inicie antes do 'app'

  db:
    image: postgres:13-alpine # Imagem leve do Postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env # Também usa as variáveis para configurar o banco

volumes:
  postgres_data: # Define um volume nomeado para persistir os dados do banco